### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by Spaceish** [egold555/Minecraft-1.8.8-PVP-Client-Series#8]
I'm getting this error:
`[23:03:46] [Client thread/INFO]: Setting user: Player359
[23:03:46] [Client thread/INFO]: (Session ID is token:0:Player359)
Exception in thread "Client thread" java.lang.AbstractMethodError: Receiver class net.minecraft.util.Cartesian$GetList does not define or inherit an implementation of the resolved method 'abstract java.lang.Object apply(java.lang.Object)' of interface com.google.common.base.Function.
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at net.minecraft.block.state.BlockState.<init>(BlockState.java:53)
[23:03:46] [Client Shutdown Thread/INFO]: Stopping server
	at net.minecraft.block.Block.createBlockState(Block.java:1210)
	at net.minecraft.block.Block.<init>(Block.java:296)
	at net.minecraft.block.Block.<init>(Block.java:302)
	at net.minecraft.block.BlockAir.<init>(BlockAir.java:13)
	at net.minecraft.block.Block.registerBlocks(Block.java:1243)
	at net.minecraft.init.Bootstrap.register(Bootstrap.java:517)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:389)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at Start.main(Start.java:11)
`

**Comment by Spaceish** [comment]
oh nvm, i just read the common-errors in the support server
